[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'raimon49/requirements.txt.vim'
on_ft = 'requirements'

[[plugins]]
repo = 'turbio/bracey.vim'
build = 'npm install --prefix server'
# hook_add = '''
#     let g:bracey_refresh_on_save = 1
# '''
on_ft = [ 'html', 'css', 'javascript' ]
on_cmd = 'Bracey'

[[plugins]]
repo = 'shime/vim-livedown'
on_ft = 'markdown'
on_cmd = 'LivedownToggle'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = [ 'html', 'css' ]

[[plugins]]
repo = 'hanschen/vim-ipython-cell'
on_ft = 'python'

[[plugins]]
repo = 'jpalardy/vim-slime'
on_ft = 'python'

[[plugins]]
repo = 'chrisbra/csv.vim'
on_ft = 'csv'

# [[plugins]]
# repo = 'OmniSharp/omnisharp-vim'
# on_ft = 'cs'
# hook_add = '''
#   let g:OmniSharp_highlighting = 0
# '''
