[[plugins]]
repo = 'voldikss/vim-floaterm'
on_cmd = ['FloatermNew', 'FloatermToggle', 'FloatermPrev', 'FloatermNext', 'FloatermSend']
depends = 'asyncrun.vim'
hook_add = '''
	let g:floaterm_width=0.4
	let g:floaterm_height=0.4
	let g:floaterm_position="bottomright"
'''
hook_source = '''
	function! s:runner_proc(opts)
		let curr_bufnr = floaterm#curr()
		if has_key(a:opts, 'silent') && a:opts.silent == 1
			FloatermHide!
		endif
		let cmd = 'cd ' . shellescape(getcwd())
		call floaterm#terminal#send(curr_bufnr, [cmd])
		call floaterm#terminal#send(curr_bufnr, [a:opts.cmd])
		stopinsert
		if &filetype == 'floaterm' && g:floaterm_autoinsert
			call floaterm#util#startinsert()
		endif
	endfunction

	let g:asyncrun_runner = get(g:, 'asyncrun_runner', {})
	let g:asyncrun_runner.floaterm = function('s:runner_proc')
  let g:asynctasks_term_pos = 'floaterm'
'''
